---
- name: Update apt cache & install needed packages
  apt: name="{{ libreswan_packages }}" state=present update_cache=yes cache_valid_time=86400

- name: Install pip-{{ libreswan_pip_version }}
  pip: name=pip version="{{ libreswan_pip_version }}"
  
- name: Install pexecpt using pip
  pip: name=pexpect version="{{ libreswan_pexecpt_version }}"

- name: Check if `gmplib` is present
  stat: path=/usr/local/lib/libgmp.a
  register: gmplib_inst

- block:
  - name: Get `gmplib` from official website
    get_url: url="{{ libreswan_gmp_url }}" dest=/tmp/

  - name: Unarchive `gmplib` tar
    unarchive: src="/tmp/{{ libreswan_gmp_version }}.tar.lz" dest=/tmp/ remote_src=yes
    
  - name: Configure and make install
    shell: bash configure --silent && make -s && make -s install && make -s check chdir="/tmp/{{ libreswan_gmp_version }}"
  when: gmplib_inst.stat.exists == False 

- name: Check if ipsec is present
  stat: path=/usr/local/sbin/ipsec
  register: ipsec_inst

- block:
  - name: Get `libreswan` from official website
    get_url: url="{{ libreswan_ipsec_url }}" dest=/tmp/

  - name: Unarchive `libreswan` tar
    unarchive: src="/tmp/{{ libreswan_version }}.tar.gz" dest=/tmp/ remote_src=yes
    
  - name: make install `libreswan`
    shell: make -s programs && make -s install chdir="/tmp/{{ libreswan_version }}"
  when: ipsec_inst.stat.exists == False

- import_tasks: configure.yml
- import_tasks: manage.yml